base: 'https://%env(APP_DOMAIN)%'
dependencies:
  - labor-digital/client_sitepackage
frontendBase: ''
headless: 1
languages:
  -
    title: English
    enabled: true
    locale: en_US.utf8
    hreflang: ''
    base: /
    websiteTitle: '%env(APP_SITENAME)%'
    navigationTitle: 'English'
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 0
  -
    title: German
    enabled: true
    base: /de/
    locale: de_DE.utf8
    navigationTitle: Deutsch
    flag: de
    hreflang: ''
    websiteTitle: '%env(APP_SITENAME)%'
    languageId: 1
rootPageId: 1
websiteTitle: '%env(APP_SITENAME)%'
