import { fileURLToPath } from 'url'
import { readdirSync } from 'node:fs'
import { addComponentsDir, addPluginTemplate, defineNuxtModule } from '@nuxt/kit'

// Register Factory layer components:
// - Ce components globally (prefix T3Ce) for nuxt-typo3's resolveDynamicComponent()
// - Content components (prefix T3Content) as auto-imports for Ce templates
// - Layout components (prefix Layout) for navbar/footer
//
// In addition, generate a plugin file at build time that registers every Ce
// wrapper via app.component(). Vue's resolveDynamicComponent() — which
// nuxt-typo3 uses to resolve T3Ce* names from CType strings — only sees
// components registered with app.component(); Nuxt's auto-import + global flag
// alone is not enough in this codepath. Generating the registration list from
// the directory eliminates the manual import list that previously caused silent
// failures when a wrapper was added but not registered (the dispatcher would
// then dump the raw content prop as JSON onto the page with no error).
export default defineNuxtModule({
  meta: {
    name: 'factory-ce-global'
  },
  setup(_options, nuxt) {
    const ceDir = fileURLToPath(new URL('../components/T3/Ce', import.meta.url))
    const ceDirNormalized = ceDir.replace(/\\/g, '/')
    const recordDir = fileURLToPath(new URL('../components/T3/Record', import.meta.url))
    const recordDirNormalized = recordDir.replace(/\\/g, '/')

    addComponentsDir({
      path: ceDir,
      extensions: ['vue'],
      prefix: 'T3Ce',
      global: true
    })
    addComponentsDir({
      path: recordDir,
      extensions: ['vue'],
      prefix: 'T3Record',
      global: true
    })
    addComponentsDir({
      path: fileURLToPath(new URL('../components/T3/Content', import.meta.url)),
      extensions: ['vue'],
      prefix: 'T3Content'
    })
    addComponentsDir({
      path: fileURLToPath(new URL('../components/Layout', import.meta.url)),
      extensions: ['vue'],
      prefix: 'Layout'
    })

    addPluginTemplate({
      filename: 'factory-register-ce.mjs',
      write: true,
      getContents() {
        const wrapperNames = readdirSync(ceDir)
          .filter((file) => file.endsWith('.vue'))
          .map((file) => file.replace(/\.vue$/, ''))
          .sort()

        const importLines = wrapperNames
          .map((name) => `import ${name} from ${JSON.stringify(`${ceDir}/${name}.vue`)}`)
          .join('\n')

        const entries = wrapperNames.map((name) => `  ${name}`).join(',\n')

        return `// AUTO-GENERATED by factory-ce-global module. Do not edit.
// Source: ${ceDir}
import { defineNuxtPlugin } from '#app'
${importLines}

const components = {
${entries}
}

export default defineNuxtPlugin((nuxtApp) => {
  for (const [name, comp] of Object.entries(components)) {
    nuxtApp.vueApp.component('T3Ce' + name, comp)
    nuxtApp.vueApp.component('LazyT3Ce' + name, comp)
  }
})
`
      }
    })

    // Record-type wrappers: symmetrical registration under T3Record prefix.
    // ReferenceList.vue uses resolveDynamicComponent('T3RecordFactory<Type>') to
    // dispatch each record to its wrapper, which needs app.component()
    // registration (same reason as T3Ce above).
    addPluginTemplate({
      filename: 'factory-register-record.mjs',
      write: true,
      getContents() {
        const wrapperNames = readdirSync(recordDir)
          .filter((file) => file.endsWith('.vue'))
          .map((file) => file.replace(/\.vue$/, ''))
          .sort()

        const importLines = wrapperNames
          .map((name) => `import ${name} from ${JSON.stringify(`${recordDir}/${name}.vue`)}`)
          .join('\n')

        const entries = wrapperNames.map((name) => `  ${name}`).join(',\n')

        return `// AUTO-GENERATED by factory-ce-global module. Do not edit.
// Source: ${recordDir}
import { defineNuxtPlugin } from '#app'
${importLines}

const components = {
${entries}
}

export default defineNuxtPlugin((nuxtApp) => {
  for (const [name, comp] of Object.entries(components)) {
    nuxtApp.vueApp.component('T3Record' + name, comp)
    nuxtApp.vueApp.component('LazyT3Record' + name, comp)
  }
})
`
      }
    })

    // In dev mode, restart Nuxt when a Ce or Record wrapper file is added or
    // removed so the auto-generated registration plugins pick up the change
    // without a manual restart. Watcher paths can arrive as absolute or
    // relative strings, so match against trailing segments.
    nuxt.hook('builder:watch', async (event, watchedPath) => {
      if ((event !== 'add' && event !== 'unlink') || !watchedPath.endsWith('.vue')) {
        return
      }
      const normalized = watchedPath.replace(/\\/g, '/')
      const inCeDir =
        normalized.includes('/components/T3/Ce/') || normalized.startsWith(ceDirNormalized)
      const inRecordDir =
        normalized.includes('/components/T3/Record/') || normalized.startsWith(recordDirNormalized)
      if (!inCeDir && !inRecordDir) {
        return
      }
      await nuxt.callHook('restart')
    })
  }
})
