name: factory/button-group
title: Button Group
description: A group of buttons displayed together.
category: factory
icon: content-text
fields:
  - identifier: alignment
    type: Select
    renderType: selectSingle
    label: Alignment
    items:
      - { label: Left, value: left }
      - { label: Center, value: center }
      - { label: Right, value: right }
    default: left
  - identifier: buttons
    type: Collection
    label: Buttons
    description: A list of buttons to display.
    fields:
      - identifier: label
        type: Text
        label: Label
      - identifier: to
        type: Link
        label: Link
      - identifier: target
        type: Select
        renderType: selectSingle
        label: Link Target
        items:
          - { label: Default, value: '' }
          - { label: New Window, value: _blank }
          - { label: Parent, value: _parent }
          - { label: Self, value: _self }
          - { label: Top, value: _top }
      - identifier: color
        type: Select
        renderType: selectSingle
        label: Color
        items:
          - { label: Primary, value: primary }
          - { label: Secondary, value: secondary }
          - { label: Neutral, value: neutral }
          - { label: Success, value: success }
          - { label: Info, value: info }
          - { label: Warning, value: warning }
          - { label: Error, value: error }
      - identifier: variant
        type: Select
        renderType: selectSingle
        label: Variant
        items:
          - { label: Solid, value: solid }
          - { label: Outline, value: outline }
          - { label: Soft, value: soft }
          - { label: Subtle, value: subtle }
          - { label: Ghost, value: ghost }
          - { label: Link, value: link }
      - identifier: size
        type: Select
        renderType: selectSingle
        label: Size
        items:
          - { label: Extra Small, value: xs }
          - { label: Small, value: sm }
          - { label: Medium, value: md }
          - { label: Large, value: lg }
          - { label: Extra Large, value: xl }
      - identifier: icon
        type: Text
        label: Icon
        description: Iconify icon name (e.g., i-lucide-arrow-right)
      - identifier: leading
        type: Checkbox
        label: Leading Icon
        description: Display the icon on the left side.
        default: 1
      - identifier: trailing
        type: Checkbox
        label: Trailing Icon
        description: Display the icon on the right side.
      - identifier: block
        type: Checkbox
        label: Full Width
        description: Render the button full width.
