services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LaborDigital\FactoryCore\:
    resource: '../Classes/*'

  LaborDigital\FactoryCore\DataProcessing\ReferenceListProcessor:
    public: true
