name: factory/text
title: Text
description: A rich text content element.
group: factory
icon: content-text
fields:
  - identifier: bodytext
    type: Textarea
    label: Text
    description: Rich text content.
    enableRichtext: true
