name: Split factory-core to mirror repo

on:
  push:
    branches:
      - master
    tags:
      - 'factory-core-v*'
  workflow_dispatch:

jobs:
  split-branch:
    if: startsWith(github.ref, 'refs/heads/')
    name: Sync master branch to mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: danharrin/monorepo-split-github-action@v2.3.0
        with:
          package_directory: 'factory-core/typo3-extension'
          repository_organization: 'labor-digital'
          repository_name: 'factory-core'
          branch: master
          user_name: 'labor-digital-bot'
          user_email: 'noreply@labor.digital'
        env:
          GITHUB_TOKEN: ${{ secrets.SUBTREE_SPLIT_TOKEN }}

  split-tag:
    if: startsWith(github.ref, 'refs/tags/factory-core-v')
    name: Mirror release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: danharrin/monorepo-split-github-action@v2.3.0
        with:
          tag: ${{ github.ref_name }}
          package_directory: 'factory-core/typo3-extension'
          repository_organization: 'labor-digital'
          repository_name: 'factory-core'
          branch: master
          user_name: 'labor-digital-bot'
          user_email: 'noreply@labor.digital'
        env:
          GITHUB_TOKEN: ${{ secrets.SUBTREE_SPLIT_TOKEN }}
